### ISSUE TITLE
После перехода на git повисает сборка проекта

### ISSUE THREAD

**Issue by svtz** [GraphLabsSuite/Web#2]
После перехода на git повисает билд проекта.
Воспроизводится как минимум у Ани и Егора.

Судя по всему, проблема в powershell-скрипте... во всяком случае, это последняя осознанная вещь, присутствующая в логе: http://pastebin.com/RMbh0EHD

**Comment by svtz** [comment]
Есть только одна гипотеза, почему это может происходить:
студия собирает несколько проектов параллельно, и наступает сама себе на пятки.
Предлагаю для начала попробовать выставить число одновременно собираемых проектов = 1.

**Comment by eakarpov** [comment]
@svtz 
Не помогло. Лог, после новой попытки сборки - http://pastebin.com/qUszfrPs

**Comment by svtz** [comment]
Гипотеза 2: флажок -noexit в команде запуска Powershell.
Он определённо вызывал у меня сомнения, но т.к. на моей машине ничего не повисало - то так и оставил... Попробовать убрать? (это по всем csproj файлам пройтись каким-нибудь тестовым редактором)

**Comment by eakarpov** [comment]
Гипотеза 2 оказалась верной - решение успешно собирается.

**Comment by svtz** [comment]
починили в #3
